import { ReactNode } from 'react'

import { Inter } from 'next/font/google'

import Header from '@/components/Layout/Header/Header'
import Footer from '@/components/Layout/Footer/Footer'
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


import './globals.scss'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Αρχική',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="el">

      <body>
        <Header />
        {children}
        <Footer />

        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          // hideProgressBar
          newestOnTop={true}
          closeOnClick={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme={'colored'}
        />
      </body>

    </html>
  )
}
